In [2]:
# Import the needed libraries
import numpy as np

**72. How to swap two rows of an array?** 

In [8]:
arr1 = np.array([[1, 2, 3],[4 ,5, 6],[7, 8, 9],[0, 2, 4]])
arr1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 2, 4]])

In [10]:
arr1[[0, 2]] = arr1[[2, 0]]
print(arr1)

[[7 8 9]
 [4 5 6]
 [1 2 3]
 [0 2 4]]


**75. How to compute averages using a sliding window over an array?**

In [22]:
def sliding_window(x, n=4) :
    

    show = np.cumsum(x, dtype=float)

    show[n:] = show[n:] - show[:-n]

    return show[n - 1:] / n

Z = np.arange(30)

print(sliding_window(Z, n=4))

[ 1.5  2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5 11.5 12.5 13.5 14.5
 15.5 16.5 17.5 18.5 19.5 20.5 21.5 22.5 23.5 24.5 25.5 26.5 27.5]
